### ISSUE TITLE
System cannot find the specified file.

### ISSUE THREAD

**Issue by harrison-matt** [manictime/manictime-client-plugin-example#5]
Looking to make a Tag plugin. I cloned your plugin example and followed your "How to use" page on GitHub. I will dig into this further...

> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Finkit.ManicTime.Shared.Plugins.ServiceProviders.ServiceProviderAssemblyLoader.EnsureAssembliesLoaded(IEnumerable`1 pluginAssemblyFileNames)

***ManicTime Version 4.0.15.0

**Comment by harrison-matt** [comment]
I identified the issue. The build was producing TagPlugin.dll assembly and the PluginSpec.json file was expecting that assembly. The project was not building and outputting that dll to the Output path.

This is a bit new to me so I wonder if I have to make a build event to include that file or if something else is more suitable.

**Comment by harrison-matt** [comment]
OK, I figured it out. For some reason, the TagPlugin.dll assembly was not building. And for whatever reason, it is now. :)
